# Base configuration for benchmark experiments
# Must be imported, as per the MN5.yaml example
defaults:
  - model: base_training
  - framework: base
  - dataset: base
  #- slurm: base
  - _self_
id:
machine:
  name: ??? # self given name, must coincide with .env-{machine.name} file
  name_pattern: ???
  modules:                        # space separated modules to load
  runtime_env_mode:               # Must provide either "venv" or "singularity"
  singularity_binds:              # singularity binds to apply on runtime
  singularity_args:               # extra singularity arguments to apply on runtine
  single_gpu_also_valid: True     # include single GPUs experiments, where it applies

experiment:
  name: "benchmark_run"           # Do not change here, only in inherited configuration
  output_dir: "results/"          # DEPRECATED(?), overwritten by RUNS_DIR global variable in 'hydra_app.py'
  repeat: 1                       # Do not change, default value for all benchmarks across computers
  yaml_filename:                  # Do not fill in, value filled during compose runtime
  env:                            # Fill in with environment variable to be available on runtime