# Base configuration for benchmark experiments
defaults:
  - base
  - _self_

machine:
  name: Jean-Zay-H100 # actual name of super computer running benchmarks
  name_pattern: Jean-Zay-H100 # configuration files naming convention pattern
  runtime_env_mode: singularity
  modules:
  - singularity

experiment:
  env: 
    NCCL_MNNVL_ENABLE: 1
    NCCL_NET_GDR_LEVEL: SYS
