# Base configuration for benchmark experiments
defaults:
  - MN5
  - _self_

machine:
  modules:
  - singularity
  singularity_container: /gpfs/scratch/bsc99/ai_operations/bsc206334/minerva-benchmarks/training/envs/benchmarks/cuda121-flash-attn/singularity_uv-runtime-ncclIB.sif
  singularity_binds:
  singularity_args:
    - "--nv"
    - "--network=host"