# Base configuration for benchmark experiments
defaults:
  - base
  - arch: MN5
  - slurm: MN5
  - env: MN5
  - _self_

machine:
  name: bsc-mn5-acc # actual name of super computer running benchmarks
  name_pattern: MN5 # configuration files naming convention pattern
  modules: 
    - singularity
  singularity_container: /gpfs/scratch/bsc99/ai_operations/bsc206334/minerva-benchmarks/training/envs/benchmarks/cuda121-flash-attn/singularity_uv-runtime-ncclIB.sif
  singularity_binds:
  singularity_args:
    - "--nv"
    - "--network=host"
  env:
    NCCL_NET: IB
    NCCL_SOCKET_IFNAME: ib0,ib1,ib2,ib3
    NCCL_IB_HCA: mlx5_0,mlx5_1,mlx5_4,mlx5_5
    NCCL_DEBUG: INFO
    NCCL_NVLS_ENABLE: "0"
    NCCL_IB_DISABLE: "0"
    CUDA_VISIBLE_DEVICES: "0,1,2,3"
    PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True,max_split_size_mb:128"
    CUDA_LAUNCH_BLOCKING: "1"
                        
