# Base configuration for benchmark experiments
defaults:
  - base
  - arch: MN5
  - slurm: MN5
  - _self_

machine:
  name: bsc-mn5-acc # actual name of super computer running benchmarks
  name_pattern: MN5 # configuration files naming convention pattern
  modules: 
    - singularity
    #- jq
    #- cuda/12.1
  python_environment: ""
  singularity_container: /home/bsc/bsc206334/Workspace/MINERVA/minerva-benchmarks/training/envs/benchmarks/cuda121-flash-attn/singularity_uv-runtime-ncclIB.sif #singularity_uv-runtime-app.sif
  #singularity_container: /home/bsc/bsc206334/Workspace/MINERVA/minerva-benchmarks/training/envs/benchmarks/cuda121-flash-attn/pytorch_2.5.1-final.sif
  singularity_binds:
    # No escaped character may be used
  #  - "--bind /opt/linpack/ACC/bench/opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so" 
  #  - "--bind /gpfs/scratch:/gpfs/scratch"
    - "--bind /dev/infiniband"
    - "--bind /dev/shm"
    #- "--bind /opt:/opt-host"
    - "--bind /apps:/apps"
    #- "--bind /gpfs/scratch"
    #- "--bind /usr/lib64/libnccl.so:/usr/lib/x86_64-linux-gnu/libnccl.so # --> libnccl.so, libmlx5.so, libibverbs.so
    - "--bind /usr/lib64/libmlx5.so:/usr/lib/x86_64-linux-gnu/libmlx5.so"
    #- "--bind /usr/lib64/libmlx5.so.1:/usr/lib/x86_64-linux-gnu/libmlx5.so.1" # --> libnccl.so, libmlx5.so, libibverbs.so
    - "--bind /usr/lib64/libibverbs.so:/usr/lib/x86_64-linux-gnu/libibverbs.so"
    #- "--bind /usr/lib64/ibibverbs.so.1:/usr/lib/x86_64-linux-gnu/ibibverbs.so.1" # --> libnccl.so, libmlx5.so, libibverbs.so
  
  singularity_args:
    # No escaped character may be used
    - "--nv"
    - "--network=host"
    #- "--env LD_PRELOAD=/usr/lib64/libnccl.so:/usr/lib64/libmlx5.so:/usr/lib64/libibverbs.so"
    #- "--env LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH"
                        
