# Base configuration for benchmark experiments
defaults:
  - base
  - _self_

machine:
  name: bsc-mn5-acc # actual name of super computer running benchmarks
  name_pattern: MN5 # configuration files naming convention pattern
  env:
    NCCL_NET: IB
    NCCL_SOCKET_IFNAME: ib0,ib1,ib2,ib3
    NCCL_IB_HCA: mlx5_0,mlx5_1,mlx5_4,mlx5_5
    NCCL_DEBUG: INFO
    NCCL_NVLS_ENABLE: "0"
    NCCL_IB_DISABLE: "0"
    CUDA_VISIBLE_DEVICES: "0,1,2,3"
    CUDA_LAUNCH_BLOCKING: "0"
experiment:
  env:
    # Copied from base.yaml to avoid overwritting
    PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True,max_split_size_mb:128"
    TORCHINDUCTOR_CACHE_DIR: "/gpfs/scratch/bsc99/ai_operations/bsc206334/minerva-benchmarks/training/.torch-inductor-cache"
    TRITON_CACHE_DIR: "/gpfs/scratch/bsc99/ai_operations/bsc206334/minerva-benchmarks/training/.triton-cache"                        
