training:
  batch_size:
    - 1
    - 2
    - 4
    - 8
  grad_accum:
    - 1
    - 2
    - 4
    - 8
    - 16
  precision:
    - "bf16"
  steps: 
    - 50
  lr: 2e-5
  optimizer: "adamw"
  gradient_checkpointing: False