defaults:
  - base
  - _self_

account: ssos027
qos: qos_gpu_h100-dev 
constraint: h100

sbatch:
  gpus_per_node: 4
  cpus_per_gpu: 24
  cpus_per_task: 96
  tasks_per_node: 1
  extra_args:
    - "--hint=nomultithread"
    - "--time=02:00:00"