account: cin_staff
qos: boost_qos_dbg
partition: boost_usr_prod


sbatch:
  gpus_per_node: 4
  cpus_per_gpu: 8
  chdir: ??
  nodes: 2
  gres: gpu:${arch.node.gpus_per_node}
  cpus_per_task: 32
  tasks_per_node: 1
  output: run-%j.out
  error: run-%j.err
  extra_args:
    - "--exclusive"
    - "--time=00:30:00"

srun:
  gpus_per_node: 4
  cpus_per_gpu: 8
  nodes: 2
  cpus_per_task: 32
  tasks_per_node: 1