account: bsc99
qos: acc_bench 
partition: acc
constraint:    
# Only set qos/partition or constraint, based on your SLURM configuration
# If using one, let the other unfilled

sbatch:
  gpus_per_node: 4
  cpus_per_gpu: 20
  chdir: ??
  nodes: 1
  gres: gpu:${arch.node.gpus_per_node}
  cpus_per_task: 80
  tasks_per_node: 1
  output: run-%j.out
  error: run-%j.err
  extra_args:
    - "--exclusive"
    - "--time=02:00:00"

srun:
  gpus_per_node: 4
  cpus_per_gpu: 20
  nodes: 1
  cpus_per_task: 80
  tasks_per_node: 1