defaults:
  - base
  - _self_

account: bsc99
qos: acc_bench 
partition: acc

sbatch:
  nodes: 6
  gres: "gpu:4"
  gpus_per_node: 4
  cpus_per_task: 20
  tasks_per_node: 4
  extra_args:
    - "--time=02-00:00:00"