name: deepspeed

parallelism:
  zero1: { min_gpus: 2 }
  zero2: { min_gpus: 2 }
  zero3: { min_gpus: 2 }
  zero3-offload: { min_gpus: 2 }

scripts:
  run:     scripts/deepspeed-common/run-deepspeed.sh
  finetune: scripts/deepspeed-common/finetune-deepspeed-pure.py
  shared:
    - scripts/deepspeed-common/gpu_monitor.py
    - scripts/deepspeed-common/utils.py
    - scripts/deepspeed-common/configs/
    - scripts/deepspeed-common/${scripts.run}
    - scripts/deepspeed-common/${scripts.finetune}
    - scripts/gpu_plots.py