# Base configuration for benchmark experiments
defaults:
  - base
  - arch: MN5
  - _self_

machine:
  name: MareNostrum5 # actual name of super computer running benchmarks
  name_pattern: MN5 # configuration files naming convention pattern
  modules: jq cuda/12.1 miniforge # space separated modules to load
  python_environment: /gpfs/scratch/bsc99/ai_operations/minerva_benchmarking/training/training_MN5/envs/fine-tune-dev-test-cuda121-hydra
  singularity_container: "no-container"
