# Base configuration for benchmark experiments
defaults:
  - trainings: combinations
  - model: base_training
  - framework: base
  - dataset: base
  #- slurm: base
  - _self_
id:
machine:
  name: ??? # self given name, must coincide with .env-{machine.name} file
  name_pattern: ???
  modules: ??? # space separated modules to load
  python_environment: ??? # path to python virtual environment
  singularity_container: ???
  single_gpu_also_valid: True

experiment:
  name: "benchmark_run"
  output_dir: "results/"
  repeat: 1
