defaults:
  - name: deepspeed
  - _self_

name: deepspeed-cuda128
python_environment: ${abs_path:envs/benchmarks/cuda128-flash-attn/.venv}
singularity_container: ${abs_path:envs/benchmarks/cuda128-flash-attn/singularity_uv-runtime.sif}
