defaults:
  - base
  - _self_

name: deepspeed-accelerate
python_environment:
singularity_container: 

parallelism_name: "" # Will be filled in during composing time
parallelism:
  zero1: { min_gpus: 2 }
  zero2: { min_gpus: 2 }
  zero3: { min_gpus: 2 }
  zero3-offload: { min_gpus: 2 }

scripts:
  run: scripts/deepspeed-common/run-deepspeed-accelerate.sh
  finetune: scripts/deepspeed-common/finetune-deepspeed-accelerate.py
  copy_files:
    - scripts/deepspeed-common/configs
    - ${framework.scripts.run}
    - ${framework.scripts.finetune}
    - scripts/shared
datasets_allowed:
  - alpaca
  - squadv2