defaults:
  - torchrun
  - _self_

python_environment: ${abs_path:envs/benchmarks/cuda121-flash-attn/.venv}
singularity_container: ${abs_path:envs/benchmarks/cuda121-flash-attn/singularity_uv-runtime.sif}
