training:
  batch_size: 1
  grad_accum: 1
  precision: "bf16"
  steps: 50
  lr: 2e-5
  optimizer: "adamw"
  gradient_checkpointing: True
  enable_compile: True
  epochs: null

combinations:
  batch_sizes: [1, 4, 8]
  precisions: ["bf16"]
  grad_accums: [8, 16]
  lr: [2e-5] 
  optimizer: ["adamw"]
  gradient_checkpointing: [True]    # Has no effect, by default checkpointing is enabled for all
                                    # ToDO: Parameterize
  enable_compile: [False, True]
